### ISSUE TITLE
Render bug (NullPointerException)

### ISSUE THREAD

**Issue by staboness** [staboness/Java_Game#1]
This occurs randomly:
Exception in thread "Thread-0" java.lang.NullPointerException
	at java.base/java.util.LinkedList.node(LinkedList.java:581)
	at java.base/java.util.LinkedList.get(LinkedList.java:481)
	at com.wavegame.main.Handler.render(Handler.java:20)
	at com.wavegame.main.Game.render(Game.java:75)
	at com.wavegame.main.Game.run(Game.java:112)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by staboness** [comment]
Method "clearEnemies" clears everything from linkedlist, render method trying to render elements before they are actually in list.

**Comment by staboness** [comment]
Decreasing number of menu particles make error occur less often
